name: Pipelines Drift Detection
run-name: "[GWP]: Pipelines Drift Detection"
on:
  # Uncomment to enable scheduled Drift Detection
  # schedule:
  #  - cron: '15 12 * * 1'
  workflow_dispatch:
    inputs:
      pipelines_drift_detection_filter:
        description: Limit drift detection to units matching filter https://docs.gruntwork.io/2.0/docs/pipelines/guides/running-drift-detection#drift-detection-filter
        type: string
      pipelines_drift_detection_branch:
        description: The branch name used for drift remediation PRs
        default: drift-detection
        type: string

permissions:
  id-token: write # Required to assume OIDC roles when using default GITHUB_TOKEN
  actions: read # Required to manage artifacts via REST API when using default GITHUB_TOKEN

jobs:
  GruntworkPipelines:
    uses: gruntwork-io/pipelines-workflows/.github/workflows/pipelines-drift-detection.yml@{{ .PipelinesWorkflowsRef }}
    with:
      pipelines_drift_detection_filter: ${{ "{{" }} inputs.pipelines_drift_detection_filter {{ "}}" }}
      pipelines_drift_detection_branch: ${{ "{{" }} inputs.pipelines_drift_detection_branch {{ "}}" }}
